version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # Para conexión desde Node.js
      - "15672:15672"   # Interfaz web de RabbitMQ
    hostname: rabbitmq

  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq

  producer:
    build: ./producer
    depends_on:
      - rabbitmq
